//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertising2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertisingsSet
    {
        public int Id { get; set; }
        public int IdOrganizations { get; set; }
        public int IdNewspapers { get; set; }
        public string IssueOfNewspapers { get; set; }
        public string AdvertisingVolume { get; set; }
    
        public virtual NewspaperSet NewspaperSet { get; set; }
        public virtual OrganizationsSet OrganizationsSet { get; set; }
    }
}
